spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shoppingcart
    username: root
    password: example
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port : 8080